In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
island = ([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 1, 1, 1, 1, 0, 0, 0, 1, 1],
            [0, 0, 1, 1, 1, 0, 1, 1, 1, 1],
            [0, 0, 1, 1, 0, 0, 1, 1, 1, 1],
            [0, 1, 1, 1, 0, 0, 1, 1, 1, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
            [0, 0, 0, 1, 1, 1, 0, 0, 1, 0],
            [0, 0, 0, 1, 1, 1, 1, 0, 0, 0],
            [0, 0, 0, 1, 1, 1, 1, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 1, 0, 0, 0]])
island = np.array(island) ###array=10*10
print(island)

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 1 1 1 0 0 0 1 1]
 [0 0 1 1 1 0 1 1 1 1]
 [0 0 1 1 0 0 1 1 1 1]
 [0 1 1 1 0 0 1 1 1 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 1 1 1 0 0 1 0]
 [0 0 0 1 1 1 1 0 0 0]
 [0 0 0 1 1 1 1 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]]


In [3]:
def checknum(island,num):
    nums = 0
    for i in range(island.shape[0]):
        for j in range(island.shape[1]):
            if island[i,j] == num:
                nums += nums
                return 1
                break
    if nums == 0:
        return 0

In [4]:
def islandnum(island):
    n = 10 ###array=10*10
    islandnum = 2
    while (checknum(island,1) == 1): ##目前位置判斷是1
        for i in range(island.shape[0]):
            for j in range(island.shape[1]):   
                if island[i,j] == 1:
                    island[i,j] = islandnum

                    if i+1 <= n-1: ## x+1 位置判斷
                        if island[i+1,j] == 1: #判斷位置是1
                            island[i+1,j] = -1 #改成-1
                    if i-1 >= 0:   ## x-1 位置判斷
                        if island[i-1,j] == 1: #判斷位置是1
                            island[i-1,j] = -1 #改成-1
                    if j+1 <= n-1: ## y+1 位置判斷
                        if island[i,j+1] == 1: #判斷位置是1
                            island[i,j+1] = -1 #改成-1
                    if j-1 >= 0:   ## y-1 位置判斷
                        if island[i,j-1] == 1: #判斷位置是1
                            island[i,j-1] = -1 #改成-1
                    #print(island)
                    
                    while(checknum(island,-1) == 1): ##目前位置判斷是-1
                        for ii in range(island.shape[0]):
                            for jj in range(island.shape[1]):
                                if island[ii,jj] == -1:
                                    island[ii,jj] = islandnum

                                    if ii+1 <= n-1: ## x+1 位置判斷
                                        if island[ii+1,jj] == 1:
                                            island[ii+1,jj] = -1
                                    if ii-1 >= 0:   ## x-1 位置判斷
                                        if island[ii-1,jj] == 1:
                                            island[ii-1,jj] = -1
                                    if jj+1 <= n-1: ## y+1 位置判斷
                                        if island[ii,jj+1] == 1:
                                            island[ii,jj+1] = -1
                                    if jj-1 >= 0:   ## y-1 位置判斷
                                        if island[ii,jj-1] == 1:
                                            island[ii,jj-1] = -1
                                    #print(island)
                                    
                    if checknum(island,-1) == 0:
                        islandnum = islandnum + 1 
                    #print(island)
                        
    islandnum = islandnum-2 #分成幾個島，要減掉原本參數設定數值
    print(island)
    return islandnum

In [5]:
###計算島大小
def islandsize(island,num):
    islandsize = np.arange(num)*0
    for k in range(2,2+num):
        for i in range(island.shape[0]):
            for j in range(island.shape[1]):
                if island[i,j] == k: #islandnum=2
                    islandsize[k-2] = islandsize[k-2] + 1  
    return islandsize

In [6]:
num = islandnum(island)                
size = islandsize(island,num)
for l in range(num):
    print('Island',l+1,'size =',size[l])

[[0 0 0 0 0 0 0 0 0 0]
 [0 2 2 2 2 0 0 0 3 3]
 [0 0 2 2 2 0 3 3 3 3]
 [0 0 2 2 0 0 3 3 3 3]
 [0 2 2 2 0 0 3 3 3 0]
 [0 0 0 0 0 0 0 0 3 0]
 [0 0 0 4 4 4 0 0 3 0]
 [0 0 0 4 4 4 4 0 0 0]
 [0 0 0 4 4 4 4 0 0 0]
 [0 0 0 0 0 0 4 0 0 0]]
Island 1 size = 12
Island 2 size = 15
Island 3 size = 12
